version: '3'
services: 
    kafka:
        image: wurstmeister/kafka
        environment: 
            KAFKA_ADVERTISED_HOST_NAME: kafka
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    zookeeper: 
        image: zookeeper
    sender:
        depends_on:
            - kafka
        build: 
            context: .
            dockerfile: Dockerfile-A
    receiver:
        depends_on:
            - kafka
            - sender
        build: 
            context: .
            dockerfile: Dockerfile-B
        
